# Generated by Django 5.0.1 on 2024-01-18 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='avatar',
            field=models.ImageField(default=None, null=True, upload_to='static/products'),
        ),
    ]
