# Generated by Django 5.0.1 on 2024-01-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carts', '0002_alter_cartitem_total_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='total_items',
        ),
        migrations.AddField(
            model_name='cart',
            name='total_items',
            field=models.IntegerField(default=0),
        ),
    ]
