# Generated by Django 5.0.1 on 2024-01-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carts', '0004_cartitem_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
